### ISSUE TITLE
J'aimerais pouvoir trier la liste des produits en cliquant sur les en-têtes de colonnes

### ISSUE THREAD

**Issue by DjLaurentB** [JabX/CestlheureduBK#1]

**Comment by DjLaurentB** [comment]
J'aimerais pouvoir trier la liste des produits en cliquant sur les en-têtes de colonnes

**Comment by JabX** [comment]
J'ai essayé d'autres tris mais le seul utile est celui par valeur. Il faudrait inclure un filtre par nombre de couronnes dans #4 en revanche.
